name: linter

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    users: actions/checkout@v2
    
    -name: Run linter
    users: github/dtk1025@v3
    env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: 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
